include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/*.dart
    - lib/**.g.dart
    - lib/**.pbjson.dart
#  enable-experiment:
#    - non-nullable

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
