name: xmux
description: XMUX Client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  animations: ^1.1.1
  connectivity: ^0.4.9
  device_calendar: ^3.1.0
  device_info: ^0.4.2
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  easy_localization: ^2.3.2
  extended_image: ^1.1.2
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0
  firebase_database: ^4.0.0
  firebase_messaging: ^7.0.0
  firebase_remote_config: ^0.4.0
  firebase_storage: ^4.0.0
  fl_chart: ^0.11.1
  flare_flutter: ^2.0.3
  flutter_html: ^1.0.0
  flutter_mobx: ^1.1.0
  flutter_redux: ^0.6.0
  # https://github.com/darioielardi/flutter_speed_dial/issues/84
  flutter_speed_dial:
    git:
      url: https://github.com/irasekh3/flutter_speed_dial
      ref: master
  flutter_spinkit: ^4.1.2
  flutter_staggered_animations: ^0.1.2
  flutter_svg: ^0.19.0
  flutter_vpn:
    git:
      url: https://github.com/X-dea/Flutter-VPN.git
      ref: rm-ios
  font_awesome_flutter: ^8.8.1
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.12
  grpc:
    git:
      url: https://github.com/XMUMY/grpc-dart.git
      ref: rm-trailer
  html: ^0.14.0
  image: ^2.1.13
  image_editor: ^0.7.0
  image_picker: ^0.6.7
  imgur: ^1.1.0
  lottie: ^0.6.0
  mobx: ^1.2.1
  package_info: ">=0.4.1 <2.0.0"
  protobuf: ^1.0.1
  qr_flutter: ^3.2.0
  redux: ^4.0.0
  sentry: ^3.0.1
  shared_preferences: ^0.5.7
  shimmer: ^1.1.1
  tuple: ^1.0.3
  url_launcher: ^5.4.11
  waterfall_flow: ^2.0.2
  webview_flutter: ^0.3.22

dependency_overrides:
  flutter_svg: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_annotation: ^3.0.1
  json_serializable: ^3.2.5
  mobx_codegen: ^1.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/initpage.jpg
    - res/logo.png
    - res/static.json
    - res/home/news.svg
    - res/campus/
    - res/animations/
    - res/translations/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
