name: xmux
description: XMUX Client

#version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cached_network_image: ^0.7.0
  connectivity: ^0.4.2
  device_info: ^0.4.0+1
  dio: ^2.1.0
  firebase_analytics: 3.0.1
  firebase_auth: 0.11.0
  firebase_database: 3.0.0
  firebase_messaging: 5.0.1+1
  firebase_remote_config: ^0.2.0
  firebase_storage: 3.0.0
  flare_flutter: ^1.5.0
  flutter_lottie: ^0.2.0
  flutter_redux: ^0.5.3
  flutter_spinkit: ^3.1.0
  flutter_svg: ^0.12.3
  flutter_vpn: ^0.4.0
  flutter_webview_plugin: ^0.3.3
  font_awesome_flutter: ^8.4.0
  googleapis: 0.53.0
  googleapis_auth: ^0.2.7
  html: ^0.14.0
  image: ^2.0.7
  image_picker: ^0.5.2
  json_annotation: ^2.0.0
  package_info: ^0.4.0
  path_provider: ^0.5.0
  photo_view: ^0.3.1
  qr_flutter: ^2.0.0
  redux: ^3.0.0
  sentry: ^2.2.0
  travelviser_dart:
    git: git@cloud.xdea.xyz:XMUX/travelviser_dart.git
  url_launcher: ^5.0.2
  webview_flutter: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  mockito: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/initpage.jpg
    - res/logo.png
    - res/campus/ecr.svg
    - res/campus/gpa_calculator.svg
    - res/campus/geogebra.svg
    - res/campus/gpa.svg
    - res/campus/klia_express.svg
    - res/campus/travelviser.svg
    - res/campus/vpn.svg
    - res/campus/wolfram.svg
    - res/animations/stars.flr
    - res/animations/vpn.json
    - res/home/news.svg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
