name: xmus_client
description: Dart client of XMUS services.
version: 0.0.1
homepage: https://github.com/XMUMY/XMUX

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  grpc: ^3.0.0
  protobuf: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
