name: Build XMUX-Android

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Build
        run: |
          echo $CONFIG_FILE > ./lib/config.dart
          echo "${GOOGLE_SERVICES_ANDROID}" > ./android/app/google-services.json
          echo "${RELEASE_SIGN_KEY}" | base64 -d > ./android/app/x.jks
          echo "${RELEASE_SIGN_KEY_PROPERTYS}" | base64 -d > ./android/key.properties
          flutter build apk --release --target-platform=android-arm64
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
          GOOGLE_SERVICES_ANDROID: ${{ secrets.GOOGLE_SERVICES_ANDROID }}
          RELEASE_SIGN_KEY: ${{ secrets.RELEASE_SIGN_KEY }}
          RELEASE_SIGN_KEY_PROPERTYS: ${{ secrets.RELEASE_SIGN_KEY_PROPERTYS }}
      - uses: actions/upload-artifact@v2
        with:
          name: XMUX-Android
          path: build/app/outputs/flutter-apk/app-release.apk
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: XMUX-Android
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_KEY }}
          packageName: org.ctbeta.xmux.xmux
          releaseFile: app-release.apk
          track: internal
