name: CI for master branch

on:
  push:
    branches:
      - master

jobs:
  BuildWeb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-java@v1
      #   with:
      #     java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - name: Configurate
        run: cp lib/config.sample.dart lib/config.dart
      - name: Build
        run: flutter config --enable-web && flutter build web
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: app
          path: build/web
